CREATE TABLE KHACH_HANG (
    KH_MA SERIAL PRIMARY KEY,
    KH_TEN VARCHAR(150) NOT NULL,
    KH_EMAIL VARCHAR(150) UNIQUE,
    KH_SDT VARCHAR(20),
    KH_DIACHI TEXT,
    KH_MATKHAU VARCHAR(255),
    KH_NGAYTAO TIMESTAMP DEFAULT
CURRENT_TIMESTAMP
);

CREATE TABLE CUA_HANG (
    CH_MA SERIAL PRIMARY KEY,
    CH_TEN VARCHAR(255) NOT NULL,
    CH_DIACHI TEXT NOT NULL,
    CH_QUANHUYEN VARCHAR(255),
    CH_THANHPHO VARCHAR(255),
    CH_NGAYTAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE SAN_PHAM (
    SP_MA SERIAL PRIMARY KEY,
    SP_TEN VARCHAR(255) NOT NULL,
    SP_GIA NUMERIC(12,2) NOT NULL,
    SP_MOTA TEXT,
    SP_HINH VARCHAR(255),
    SP_NGAYTAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    SP_NGAYCAPNHAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE DON_HANG (
    DH_MA SERIAL PRIMARY KEY,
    KH_MA INT REFERENCES KHACH_HANG(KH_MA) ON DELETE SET NULL,
    DH_TENKH VARCHAR(255),
    DH_SDT VARCHAR(20),
    DH_DIACHI TEXT,
    DH_HTNHAN VARCHAR(50),
    CH_MA INT REFERENCES CUA_HANG(CH_MA) ON DELETE SET NULL,
    DH_TONGTIEN NUMERIC(12,2),
    DH_TRANGTHAI VARCHAR(50) DEFAULT 'pending',
    DH_NGAYTAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE CHI_TIET_DON_HANG (
    CTDH_MA SERIAL PRIMARY KEY,
    DH_MA INT REFERENCES DON_HANG(DH_MA) ON DELETE CASCADE,
    SP_MA INT REFERENCES SAN_PHAM(SP_MA) ON DELETE CASCADE,
    CTDH_SOLUONG INT NOT NULL,
    CTDH_GIA NUMERIC(12,2) NOT NULL,
    CTDH_THANHTIEN NUMERIC(12,2) NOT NULL
);

CREATE TABLE QUAN_TRI_VIEN (
    QTV_MA SERIAL PRIMARY KEY,
    QTV_TENDN VARCHAR(255) NOT NULL UNIQUE,
    QTV_MATKHAU VARCHAR(255) NOT NULL,
    QTV_NGAYTAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
