-- Migration bổ sung: khuyến mãi + các cột còn thiếu trong CUA_HANG
-- An toàn để chạy lại nhiều lần, KHÔNG xóa dữ liệu hiện có.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

ALTER TABLE CUA_HANG ADD COLUMN IF NOT EXISTS CH_SDT VARCHAR(20);
ALTER TABLE CUA_HANG ADD COLUMN IF NOT EXISTS MATINH VARCHAR(20);
ALTER TABLE CUA_HANG ADD COLUMN IF NOT EXISTS MAHUYEN VARCHAR(20);
ALTER TABLE CUA_HANG ADD COLUMN IF NOT EXISTS MAXA VARCHAR(20);
ALTER TABLE CUA_HANG ADD COLUMN IF NOT EXISTS SONHA_DUONG VARCHAR(255);
ALTER TABLE CUA_HANG ADD COLUMN IF NOT EXISTS GIO_MO_CUA VARCHAR(20);
ALTER TABLE CUA_HANG ADD COLUMN IF NOT EXISTS GIO_DONG_CUA VARCHAR(20);

CREATE TABLE IF NOT EXISTS KHUYEN_MAI (
    KM_MA SERIAL PRIMARY KEY,
    KM_TEN VARCHAR(255) NOT NULL,
    KM_MOTA TEXT,
    KM_PHANTRAM INT NOT NULL CHECK (KM_PHANTRAM BETWEEN 1 AND 100),
    KM_NGAYBATDAU DATE NOT NULL,
    KM_NGAYKETTHUC DATE NOT NULL,
    KM_TRANGTHAI BOOLEAN DEFAULT true,
    KM_NGAYTAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE SAN_PHAM ADD COLUMN IF NOT EXISTS KM_MA INT REFERENCES KHUYEN_MAI(KM_MA) ON DELETE SET NULL;
